name = "api"
compatibility_date = "2023-12-28"
main = "src/index.ts"

[vars]
MY_VAR = "my-variable"
DATABASE_URL = "postgresql://neondb_owner:5OH2SVQdpITs@ep-empty-wildflower-a2j8ae8u.eu-central-1.aws.neon.tech/Dingify2?sslmode=require"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
